name: Check URLs

on:
  push:
  pull_request:
  schedule:
    # Every day at midnight (UTC).
    # URLs can decay over time. Setting up a schedule makes it possible to be warned
    # about dead links as soon as possible.
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: urls-checker
      uses: urlstechie/urlchecker-action@master
      with:
        # A comma-separated list of file types to cover in the URL checks
        file_types: .md

        # Choose whether to include file with no URLs in the prints.
        print_all: false

        # The timeout seconds to provide to requests, defaults to 5 seconds
        timeout: 5

        # A comma separated patterns to exclude during URL checks
        exclude_patterns: https://awesome.re,https://godotengine.org,https://www.youtube.com
